repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.9
      hooks:
          - id: ruff
            stages: [pre-commit]
          - id: ruff-format
            stages: [pre-commit]

    - repo: local
      hooks:
          - id: run-pytest
            name: Run tests with pytest
            entry: pytest
            language: system
            types: [python]
            pass_filenames: false
            stages: [pre-commit]

    - repo: local
      hooks:
          - id: commit-msg-check
            name: Commit Message Check
            entry: python3 .githooks/validate_commit_msg.py
            language: system
            stages: [commit-msg]
